### ISSUE TITLE
Feedback on sorting algorithms

### ISSUE THREAD

**Issue by Anisha7** [Sukhrobjon/CS-2.1-Trees-Sorting#1]
What was great:

- Good job on implementing your is_sorting function efficiently!
- Good job on successfully implementing your sorting algorithms!
Here's some feedback to improve:
- Try adding a couple more test cases as specified by the TODO's!
- Merge sort algorithms need to be in place! That's the reason the unit tests are failing :(

**Comment by Sukhrobjon** [comment]
@Anisha7 Thank you, I have updated merge sort to be inplace and passed all tests.

**Comment by Anisha7** [comment]
If you make your split_sort_merge in place as well `items=merged_list`, then it will pass all the tests.

**Comment by Anisha7** [comment]
Add `items[:] = merged_list` to make split_sort_merge in place as well, so all your tests can pass!
