### ISSUE TITLE
Feedback on prefix trees

### ISSUE THREAD

**Issue by Anisha7** [Sukhrobjon/CS-2.1-Trees-Sorting#2]
Great job on completing the prefix tree! 
* You can further challenge yourself by working on time and space complexities for each prefix tree method. You would be expected to do this in interviews, and it would be good practice :)
* Your complete method is failing. It seems to add different combinations of the words in the prefix tree, which is not valid. Ex. If apple is in the tree, then apple is valid but pplea is not.

**Comment by Sukhrobjon** [comment]
I have fixed that issue, thank you for your feedback. @Anisha7
