### ISSUE TITLE
Feedback on heaps, priority queues, and integer sorting algorithms

### ISSUE THREAD

**Issue by Anisha7** [Sukhrobjon/CS-2.1-Trees-Sorting#3]
Great work on completing these challenges. Here's some feedback to improve your code:
- Your priority queue does not work as expected. Your front, push_pop, and dequeue functions should return the actual item! So if I inserted “apple” with priority 0, the item is “apple”. Don't return the whole tuple. I tried running your code by these tests:
```
if __name__ == "__main__":
    PQ = PriorityQueue()
    assert(PQ.is_empty())
    assert(PQ.length() == 0)
    PQ.enqueue("apple", 2)
    assert(PQ.length() == 1)
    assert(PQ.front() == "apple")
    assert(PQ.length() == 1)
    PQ.enqueue("orange", 0)
    assert(PQ.length() == 2)
    assert(PQ.front() == "orange")
    assert(PQ.length() == 2)
    assert(PQ.dequeue() == "orange")
    assert(PQ.length() == 1)
    assert(PQ.push_pop("banana", 4) == "apple")
    assert(PQ.length() == 1)
    assert(PQ.front() == "banana")
    assert(PQ.length() == 1)
    print("PASSED")
```

**Comment by Sukhrobjon** [comment]
@Anisha7 I fixed the issue, I forgot the right return type for those methods. It should pass the tests now
